service: meadow
frameworkVersion: '2'

package:
  artifact: .meadow.zip

provider:
  name: aws
  runtime: python3.8
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - '*'
    - Effect: Allow
      Action:
        - ses:*
      Resource:
        - '*'
    - Effect: Allow
      Action:
        - ssm:*
      Resource:
        - '*'

functions:
  signup:
    handler: handlers/signup.signup
    events:
      - httpApi: "POST /signup"
  validate:
    handler: handlers/validate.validate
    events:
      - httpApi: "GET /validate"
  unsubscribe:
    handler: handlers/unsubscribe.unsubscribe
    events:
      - httpApi: "GET /unsubscribe"

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: meadow-users
        AttributeDefinitions:
          - AttributeName: partitionKey
            AttributeType: S
          - AttributeName: sortKey
            AttributeType: S
        KeySchema:
          - AttributeName: partitionKey
            KeyType: HASH
          - AttributeName: sortKey
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1