service: meadow
frameworkVersion: '2'

package:
  exclude:
    - "**"
  include:
    - "handlers/*"

provider:
  name: aws
  runtime: python3.8

functions:
  newsletter_signup:
    handler: handlers/newsletter.signup
    events:
      - httpApi: "POST /newsletter_signup"