service: meadow
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8

functions:
  addMember:
    handler: handler.addMember
    events:
      - sechedule: rate(5 minutes)
    environment:
      DDB_TABLE:
        Fn::GetAtt:
          - Members
          - Arn

resources:
  Resources:
    Members:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: "meadow-members"