service: meadow
frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8

functions:
  newsletter_signup:
    handler: handler.newsletter_signup
    events:
      - httpApi: "POST /newsletter_signup"