version: 2.1

jobs:
  deploy_test_destroy:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout

      - run:
          name: Install Serverless CLI and dependencies
          command: |
            sudo npm i -g serverless
            npm install
      
      - run:
          name: Install Python, Pip, Pytest and Pytest-BDD
          command: |
            sudo apt update
            sudo apt install python3-pip
            sudo pip3 install pytest-bdd

      - run:
          name: Deploy Meadow
          command: serverless deploy --conceal

      - run:
          name: Fetch API Gateway domain
          command: serverless info|grep "/newsletter_signup"|cut -d '/' -f3 > /tmp/test_domain


      - run:
          name: Run tests
          command: |
            TEST_DOMAIN=$(cat /tmp/test_domain)
            pytest
      
      - run:
          name: Remove Meadow
          command: serverless remove

workflows:
  pull-request:
    jobs:
      - deploy_test_destroy:
          context: testing
